name: "Action Workflow"
description: "This is the composite action"

inputs:
  name:
    description: "Name"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Print name
      run: |
        echo "Name: ${{ inputs.name }}"
      shell: bash
