name: Action Workflow
run-name: ${{ inputs.name }} trigger workflow

inputs:
  name:
    description: "Name"
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Print name
      id: print-name
      run: |
        echo "Name: ${{ inputs.name }}"
