name: Action Workflow

inputs:
  name:
    description: "Name"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Print name
      id: print-name
      run: |
        echo "Name: ${{ inputs.name }}"
      shell: bash
